# Generated by Django 3.1.1 on 2022-12-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('pieceno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ram', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
